version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=VgPJpyArnNArMLxnxcTyFDXJVshVzIbM
      - POSTGRES_DB=railway
      - POSTGRES_HOST=postgres.railway.internal
      - POSTGRES_PORT=5432
      - SECRET_KEY=mysecretkey
      # Set FRONTEND_URL to a placeholder; Railway will override this in its settings:
      - FRONTEND_URL=http://localhost:8000/static/index.html
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=VgPJpyArnNArMLxnxcTyFDXJVshVzIbM
      - POSTGRES_DB=railway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
