version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - opensearch
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Piyush@123
      - POSTGRES_DB=globetrotter
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_USER=admin
      - OPENSEARCH_PASSWORD=Piyush@123
      - OPENSEARCH_INDEX=destinations
      - SECRET_KEY=mysecretkey
      - FRONTEND_URL=http://localhost:8000/static/index.html
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Piyush@123
      - POSTGRES_DB=globetrotter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  opensearch:
    image: opensearchproject/opensearch:2.19.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Piyush@123
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9201:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

volumes:
  postgres_data:
  opensearch_data:
